
spring:
  application:
    name: dashscope-demo
  ai:
    dashscope:
      api-key: sk-xxxxx # 示例密钥，运行前请替换为真实 Key
      chat:
        options:
          top-k: 1
          top-p: 1
          model: deepseek-r1
server:
  port: 8081
