spring:
  application:
    name: qwen32-demo
  ai:
    dashscope:
      #
      api-key: sk-783498598b17422487f136b05970a488
      chat:
        options:
          top-k: 1
          top-p: 1
          model: qwq-plus
server:
  port: 8082
